version: "3.9"

services:
  app:
    build: .
    container_name: my_app
    ports:
      - "3000:3000" # Expose app on host port 3000
    environment:
      DB_HOST: host.docker.internal # Connect to host machine
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: kkn_db
      APP_HOST: 0.0.0.0 # Make server accessible from host
      APP_PORT: 3000
